spring:
    application:
        name: gateway-service
    config:
        # import: optional:configserver:http://localhost:8098/
        import: configserver:http://config:8098/
management:
    endpoints:
        web:
            exposure:
                include: "*"
            